/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_NDKHelper */

#ifndef _Included_com_example_myapplication_NDKHelper
#define _Included_com_example_myapplication_NDKHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_NDKHelper
 * Method:    initndkhelper
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_NDKHelper_initndkhelper
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
